export function OutputsPage() {
  return (
    <div style={{padding:'32px'}}>
      <h1 style={{fontSize:'var(--text-xl)',fontWeight:700,color:'var(--color-text)',marginBottom:'8px'}}>Outputs</h1>
      <p style={{color:'var(--color-text-muted)',fontSize:'var(--text-sm)'}}>Files and results generated by agents will appear here.</p>
    </div>
  )
}
